test retry mechanism

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -32,12 +32,19 @@ jobs:
         run: echo "VERSION_NAME=$(git describe --tags HEAD | sed 's/^v//')" >> $GITHUB_ENV
 
       - name: Build variant of app
-        uses: eskatos/gradle-command-action@v1
-        with:
-          wrapper-cache-enabled: true
-          dependencies-cache-enabled: true
-          configuration-cache-enabled: true
-          arguments: app:assembleRelease -PversionName=${{ env.VERSION_NAME }}
+        run: # Retry 3 times before the steps actually fails
+          (echo "===== Gradle Build Attempt: 1 ====" && gradlew app:assembleRelease -PversionName=$VERSION_NAME) || \
+          (echo "===== Gradle Build Attempt: 2 ====" && gradlew app:assembleRelease -PversionName=$VERSION_NAME) || \
+          (echo "===== Gradle Build Attempt: 3 ====" && gradlew app:assembleRelease -PversionName=$VERSION_NAME) || \
+          (echo "==== Gradle Build Step Failed ====" && exit 1)
+
+      # - name: Build variant of app
+      #   uses: eskatos/gradle-command-action@v1
+      #   with:
+      #     wrapper-cache-enabled: true
+      #     dependencies-cache-enabled: true
+      #     configuration-cache-enabled: true
+      #     arguments: app:assembleRelease -PversionName=${{ env.VERSION_NAME }}
 
       - name: Create signed APKs
         id: sign_app
